# -*- coding: utf-8 -*-
"""humor_app.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tVb3lXjlZR6m0-Tt6jm7Xwrj3hEoe25F
"""

#import pip

#pip install streamlit
import pickle
import streamlit as st
from PIL import Image
  
# loading in the model to predict on the data

pickle_in = open('/home/mirana/Downloads/group 5/classifier.pkl', 'rb')
classifier = pickle.load(pickle_in)
  
def welcome():
    return 'welcome all'
  
# defining the function which will make the prediction using 
# the data which the user inputs
def prediction(questions_):  
   
    prediction = classifier.predict([[questions_]])
    print(prediction)
    return prediction
      
  
# this is the main function in which we define our webpage 
def main():
      # giving the webpage a title
    st.title("humor detection")
      
    # here we define some of the front end elements of the web page like 
    # the font and background color, the padding and the text to be displayed
    html_temp ='''
    <div style ="background-color:yellow;padding:13px">
    <h1 style ="color:black;text-align:center;">Streamlit humour Classifier ML App </h1>
    </div>'''
    
      
    # this line allows us to display the front end aspects we have 
    # defined in the above code
    st.markdown(html_temp, unsafe_allow_html = True)
      
    # the following lines create text boxes in which the user can enter 
    # the data required to make the prediction
    question = st.text_input("question")

    result ="Type here"
      
    # the below line ensures that when the button called 'Predict' is clicked, 
    # the prediction function defined above is called to make the prediction 
    # and store it in the variable result
    if st.button("Predict"):
        result = prediction(question)
    st.success('The output is {}'.format(result))
     
if __name__=='__main__':
    main()

